---
- name: NTP and OSPF configuration on mikrotik
  hosts: chr_routers
  gather_facts: false
  tasks:

    - name: NTP
      community.routeros.command:
        commands:
          - "/system ntp client set enabled=yes"
          - "/system ntp client set primary-ntp={{ ntp_server }}"
          - "/system ntp client set server-dns-names={{ ntp_server }}"

    - name: Create loopback
      community.routeros.command:
        commands:
          - /interface bridge add name=loopback0

    - name: Add ip to loopback
      community.routeros.command:
        commands:
          - "/ip address add address={{ router_id }}/32 interface=loopback0"

    - name: Set routerID to ospf
      community.routeros.command:
        commands:
          - "/routing ospf instance add name=v2inst version=2 router-id={{ router_id }}"

    - name: Add ospf network to backbone
      community.routeros.command:
        commands:
          - /routing ospf area add name=backbone_v2 area-id=0.0.0.0 instance=v2inst

    - name: Add template
      community.routeros.command:
        commands:
          - /routing ospf interface-template add networks=0.0.0.0/0 area=backbone_v2

    - name: gather all facts
      community.routeros.facts:
        gather_subset: all

    - name: gather ospf instance facts
      debug:
        var: ansible_net_ospf_instance

    - name: gather ospf neighbours
      debug:
        var: ansible_net_ospf_neighbor